[package]
name = "skynet"
version = "0.1.0"
authors = ["Mahmut Bulut <vertexclique@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
discord = "0.8.0"
cached = "0.9.0"
serde_json = "0.8"
rand = "0.7.0"
